[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 2
  wrap_comments = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
